Repository codestates-seb/seb41_main_013, pull requests merged in 2023-01, with the labels that each got.

#2 [Chore] server 개발환경 세팅
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/mainproject/MainProjectApplication.java
  server/src/main/resources/application.yml
  server/src/test/java/mainproject/MainProjectApplicationTests.java
Labels: documentation

#3 [Chore] server 개발환경 세팅 - domain, global 디렉토리 추가
  README.md
  server/src/main/java/mainproject/domain/challenge/.gitkeeper
  server/src/main/java/mainproject/domain/challenger/.gitkeeper
  server/src/main/java/mainproject/domain/comment/.gitkeeper
  server/src/main/java/mainproject/domain/member/.gitkeeper
  server/src/main/java/mainproject/domain/post/.gitkeeper
  server/src/main/java/mainproject/domain/snapshot/.gitkeeper
  server/src/main/java/mainproject/global/.gitkeeper
Labels: documentation

#17 [FE]chore: 라이브러리 set-up
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.test.js
  client/src/components/theme.js
  client/src/counter/Counter.js
  client/src/counter/counterSlice.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/src/store.js
Labels: FE, chore

#19 [FE] docs: 디렉토리, 컴포넌트 추가
  client/src/components/Avatar.js
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/Challenge.js
  client/src/components/ChallengeInfo.js
  client/src/components/Comment.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Input.js
  client/src/components/Loading.js
  client/src/components/Logout.js
  client/src/components/Modal.js
  client/src/components/NavItem.js
  client/src/components/NoData.js
  client/src/components/Post.js
  client/src/components/Tag.js
  client/src/components/WriterInfo.js
  client/src/data/dummy.js
  client/src/pages/ChallengeDetail.js
  client/src/pages/Community.js
  client/src/pages/CommunityCategoryBoard.js
  client/src/pages/CreateChallenge.js
  client/src/pages/CreatePost.js
  client/src/pages/FindPassword.js
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/Login.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyChallengeOthers.js
  client/src/pages/MyChallengeUpload.js
  client/src/pages/MyPage.js
  client/src/pages/PostDetail.js
  client/src/pages/SignUp.js
  client/src/pages/UpdatePost.js
  client/src/pages/UserCompleteChallenge.js
  client/src/pages/UserCreateChallenge.js
  client/src/pages/UserPasswordChange.js
  client/src/pages/UserProfileEdit.js
  client/src/router/Router.js
Labels: FE, docs

#23 [BE] feat: 챌린지 CRUD 구현
  server/build.gradle
  server/src/main/java/mainproject/MainProjectApplication.java
  server/src/main/java/mainproject/domain/challenge/.gitkeeper
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengePostDto.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengeResponseDto.java
  server/src/main/java/mainproject/domain/challenge/entity/Challenge.java
  server/src/main/java/mainproject/domain/challenge/entity/ChallengeStatus.java
  server/src/main/java/mainproject/domain/challenge/entity/Frequency.java
  server/src/main/java/mainproject/domain/challenge/mapper/ChallengeMapper.java
  server/src/main/java/mainproject/domain/challenge/repository/ChallengeRepository.java
  server/src/main/java/mainproject/domain/challenge/service/ChallengeService.java
  server/src/main/java/mainproject/domain/image/controller/ImageController.java
  server/src/main/java/mainproject/domain/image/dto/ImageResponseDto.java
  server/src/main/java/mainproject/domain/image/entity/Image.java
  server/src/main/java/mainproject/domain/image/mapper/ImageMapper.java
  server/src/main/java/mainproject/domain/image/repository/ImageRepository.java
  server/src/main/java/mainproject/domain/image/service/ImageService.java
  server/src/main/java/mainproject/global/category/Category.java
  server/src/main/java/mainproject/global/exception/ExceptionCode.java
Labels: BE, feat, fix

#26 [FE] feat : 커뮤니티 관련 컴포넌트 생성 #10
  client/package-lock.json
  client/public/images/미모티콘.png
  client/src/App.css
  client/src/App.js
  client/src/components/Avatar.js
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/Comment.js
  client/src/components/Modal.js
  client/src/components/Post.js
  client/src/components/PostSummary.js
  client/src/components/WriterInfo.js
Labels: FE, feat

#27 [FE]feat: 헤더, 챌린지, 네브바 관련 컴포넌트 생성
  client/src/App.css
  client/src/components/Category.js
  client/src/components/Challenge.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/NavItem.js
  client/src/components/theme.js
  client/src/images/challenge.png
  client/src/images/etc.png
  client/src/images/example2.jpeg
  client/src/images/exercise.png
  client/src/images/exercise2.png
  client/src/images/life.png
  client/src/images/town.png
Labels: FE, feat, design

#30 #8 - style: 컴포넌트명 변경
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/Modal.js
Labels: FE, style

#32 #11 - feat: 페이지 크기 조절, 마이페이지 버튼 위치 수정
  client/package-lock.json
  client/package.json
  client/public/images/example2.jpeg
  client/src/App.css
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/Challenge.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/ImageUploader.js
  client/src/components/Input.js
  client/src/components/Modal.js
  client/src/components/MypageSetting.js
  client/src/components/NavItem.js
  client/src/components/theme.js
  client/src/index.js
  client/src/pages/Home.js
  client/src/pages/MyPage.js
  client/src/pages/UserCompleteChallenge.js
  client/src/pages/UserCreateChallenge.js
  client/src/pages/UserPasswordChange.js
  client/src/pages/UserProfileEdit.js
Labels: FE, feat

#36 #8 - feat: 홈, 마이챌린지 관련 페이지 UI 구현
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/ChallengeItem.js
  client/src/components/Footer.js
  client/src/components/ImageUploader.js
  client/src/components/Input.js
  client/src/components/ProgressBar.js
  client/src/index.css
  client/src/index.js
  client/src/pages/ChallengeDetail.js
  client/src/pages/CreateChallenge.js
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyChallengeOthers.js
  client/src/pages/MyChallengeUpload.js
  client/src/pages/MyPage.js
  client/src/router/Router.js
Labels: FE, feat, chore, design

#38 #7,8 - feat: 로그인/ 회원가입 페이지 UI 작업
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/Challenge.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Input.js
  client/src/components/MypageSetting.js
  client/src/components/NavItem.js
  client/src/pages/CreateChallenge.js
  client/src/pages/FindPassword.js
  client/src/pages/Login.js
  client/src/pages/MyPage.js
  client/src/pages/SignUp.js
  client/src/pages/UserPasswordChange.js
  client/src/pages/UserProfileEdit.js
  client/src/router/Router.js
Labels: FE, feat

#40 #10 - feat : 커뮤니티 관련 페이지 UI 구현 & 기능 일부 구현
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/Comment.js
  client/src/components/Footer.js
  client/src/components/Input.js
  client/src/components/PostSummary.js
  client/src/components/SearchInput.js
  client/src/components/WriteComment.js
  client/src/components/WriterInfo.js
  client/src/data/dummy.js
  client/src/function/postFunction.js
  client/src/index.css
  client/src/pages/Community.js
  client/src/pages/CommunityCategoryBoard.js
  client/src/pages/CreatePost.js
  client/src/pages/PostDetail.js
  client/src/pages/UpdatePost.js
  client/src/router/Router.js
Labels: FE, feat, fix, style

#41 #8 - feat: 홈, 마이챌린지 관련 페이지 UI 구현
  client/package-lock.json
  client/package.json
  client/src/components/ChallengeItem.js
  client/src/components/Footer.js
  client/src/components/Input.js
  client/src/components/Modal.js
  client/src/pages/ChallengeDetail.js
  client/src/pages/CreateChallenge.js
  client/src/pages/CreatePost.js
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyChallengeUpload.js
  client/src/pages/UpdatePost.js
Labels: FE, feat, chore

#49 #34 - feat: API 문서화
  server/build.gradle
  server/src/main/java/mainproject/domain/challenge/dto/ChallengeResponseDto.java
  server/src/main/java/mainproject/domain/challenge/entity/Challenge.java
  server/src/main/java/mainproject/domain/challenge/mapper/ChallengeMapper.java
  server/src/main/java/mainproject/domain/challenger/Entity/Challenger.java
  server/src/main/java/mainproject/domain/challenger/Mapper/ChallengerMapper.java
  server/src/main/java/mainproject/domain/snapshot/Mapper/SnapshotMapper.java
  server/src/main/java/mainproject/global/config/SwaggerConfiguration.java
  server/src/main/resources/application.yml
Labels: BE, feat

#50 #35 feat/be board 검색기능추가
  server/src/main/java/mainproject/domain/board/controller/BoardController.java
  server/src/main/java/mainproject/domain/board/entity/Board.java
  server/src/main/java/mainproject/domain/board/mapper/BoardMapper.java
  server/src/main/java/mainproject/domain/board/respository/BoardRepository.java
  server/src/main/java/mainproject/domain/board/service/BoardService.java
  server/src/main/java/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject/domain/comment/dto/CommentPatchDto.java
  server/src/main/java/mainproject/domain/comment/dto/CommentPostDto.java
  server/src/main/java/mainproject/domain/comment/dto/CommentResponseDto.java
  server/src/main/java/mainproject/domain/comment/entity/Comment.java
  server/src/main/java/mainproject/domain/comment/repository/CommentRepository.java
  server/src/main/java/mainproject/domain/comment/service/CommentService.java
  server/src/main/java/mainproject/global/dto/MultiResponseDto.java
  server/src/main/java/mainproject/global/dto/PageInfo.java
  server/src/main/java/mainproject/global/exception/ExceptionCode.java
  server/src/main/java/mainproject/global/page/PageInfo.java
Labels: BE

#51 #36 - refactor/be: security 코드 수정
  server/src/main/java/mainproject/domain/member/service/MemberService.java
  server/src/main/java/mainproject/domain/security/config/SecurityConfiguration.java
Labels: BE, refactor

#55 #34 - feat: API 문서화
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengePostDto.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengeResponseDto.java
  server/src/main/java/mainproject/domain/challenge/entity/Challenge.java
  server/src/main/java/mainproject/domain/challenge/service/ChallengeService.java
  server/src/main/java/mainproject/domain/challenger/Service/ChallengerService.java
  server/src/main/java/mainproject/global/config/SwaggerConfiguration.java
  server/src/main/java/mainproject/global/exception/ExceptionCode.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: BE, feat

#56 #34 - feat: API 문서화
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/global/config/SwaggerConfiguration.java
Labels: BE, feat

#57 #11 - style: 전체 페이지 크기 조절, 마이페이지 컴포넌트 크기 조절
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/Challenge.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/MypageSetting.js
  client/src/components/NavItem.js
  client/src/index.css
  client/src/index.js
  client/src/pages/FindPassword.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/MyPage.js
  client/src/pages/SignUp.js
  client/src/pages/UserCompleteChallenge.js
  client/src/pages/UserCreateChallenge.js
  client/src/pages/UserPasswordChange.js
  client/src/pages/UserProfileEdit.js
  client/src/router/Router.js
Labels: FE, style

#61 #34 - feat: API 문서화
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/service/ChallengeService.java
  server/src/main/java/mainproject/domain/challenger/Controller/ChallengerController.java
  server/src/main/java/mainproject/domain/challenger/Dto/ChallengerPostDto.java
  server/src/main/java/mainproject/domain/challenger/Service/ChallengerService.java
  server/src/main/java/mainproject/domain/security/config/SecurityConfiguration.java
  server/src/main/java/mainproject/domain/snapshot/Controller/SnapshotController.java
  server/src/main/java/mainproject/domain/snapshot/Dto/SnapshotPostDto.java
Labels: BE, feat

#62 #38Feat/멤버 로그인 API 문서화
  server/src/main/java/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/mainproject/domain/security/controller/AuthController.java
  server/src/main/java/mainproject/domain/security/dto/LoginDto.java
Labels: BE, feat

#63 #10 - style : % 단위로 css 수정
  client/package-lock.json
  client/src/components/Button.js
  client/src/components/Category.js
  client/src/components/Comment.js
  client/src/components/Input.js
  client/src/components/Modal.js
  client/src/components/PostSummary.js
  client/src/components/SearchInput.js
  client/src/components/WriteComment.js
  client/src/components/WriterInfo.js
  client/src/pages/Community.js
  client/src/pages/CommunityCategoryBoard.js
  client/src/pages/CreatePost.js
  client/src/pages/PostDetail.js
  client/src/pages/UpdatePost.js
Labels: FE, style, design

#58 #37 fix : be-security 코드 수정
  server/src/main/java/mainproject/domain/board/controller/BoardController.java
  server/src/main/java/mainproject/domain/board/dto/BoardPatchDto.java
  server/src/main/java/mainproject/domain/board/dto/BoardPostDto.java
  server/src/main/java/mainproject/domain/board/service/BoardService.java
  server/src/main/java/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject/domain/comment/dto/CommentPostDto.java
  server/src/main/java/mainproject/domain/comment/repository/CommentRepository.java
  server/src/main/java/mainproject/domain/security/config/SecurityConfiguration.java
Labels: BE

#69 #38 feat/be-board 게시판 댓글 수정 삭제 기능 수정
  server/src/main/java/mainproject/domain/board/controller/BoardController.java
  server/src/main/java/mainproject/domain/board/dto/BoardPostDto.java
  server/src/main/java/mainproject/domain/board/entity/Board.java
  server/src/main/java/mainproject/domain/board/mapper/BoardMapper.java
  server/src/main/java/mainproject/domain/board/service/BoardService.java
  server/src/main/java/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject/domain/comment/dto/CommentPostDto.java
  server/src/main/java/mainproject/domain/comment/service/CommentService.java
  server/src/main/java/mainproject/domain/security/config/SecurityConfiguration.java
Labels: BE

#71 #34 - feat: API 문서화
  server/src/main/java/mainproject/domain/board/dto/BoardPatchDto.java
  server/src/main/java/mainproject/domain/board/dto/BoardPostDto.java
  server/src/main/java/mainproject/domain/board/dto/BoardResponseDto.java
  server/src/main/java/mainproject/domain/board/entity/Board.java
  server/src/main/java/mainproject/domain/board/mapper/BoardMapper.java
  server/src/main/java/mainproject/domain/board/service/BoardService.java
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengePostDto.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengeResponseDto.java
  server/src/main/java/mainproject/domain/challenge/entity/Challenge.java
  server/src/main/java/mainproject/domain/challenge/mapper/ChallengeMapper.java
  server/src/main/java/mainproject/domain/challenge/service/ChallengeService.java
  server/src/main/java/mainproject/domain/challenger/Dto/ChallengerResponseDto.java
  server/src/main/java/mainproject/domain/challenger/Entity/Challenger.java
  server/src/main/java/mainproject/domain/challenger/Mapper/ChallengerMapper.java
  server/src/main/java/mainproject/domain/challenger/Service/ChallengerService.java
  server/src/main/java/mainproject/domain/comment/dto/CommentResponseDto.java
  server/src/main/java/mainproject/domain/comment/entity/Comment.java
  server/src/main/java/mainproject/domain/comment/mapper/CommentMapper.java
  server/src/main/java/mainproject/domain/image/controller/ImageController.java
  server/src/main/java/mainproject/domain/image/entity/Image.java
  server/src/main/java/mainproject/domain/image/service/ImageService.java
  server/src/main/java/mainproject/domain/member/dto/MemberPatchDto.java
  server/src/main/java/mainproject/domain/member/dto/MemberPostDto.java
  server/src/main/java/mainproject/domain/member/dto/MemberResponseDto.java
  server/src/main/java/mainproject/domain/member/entity/Member.java
  server/src/main/java/mainproject/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject/domain/member/service/MemberService.java
  server/src/main/java/mainproject/domain/security/config/SecurityConfiguration.java
  server/src/main/java/mainproject/domain/snapshot/Dto/SnapshotPostDto.java
  server/src/main/java/mainproject/domain/snapshot/Dto/SnapshotResponseDto.java
  server/src/main/java/mainproject/domain/snapshot/Entity/Snapshot.java
  server/src/main/java/mainproject/domain/snapshot/Mapper/SnapshotMapper.java
  server/src/main/java/mainproject/global/config/SwaggerConfiguration.java
Labels: BE, feat, refactor

#72 #38 refactor: SecurityConfiguration 코드 추가
  server/src/main/java/mainproject/domain/security/config/SecurityConfiguration.java
Labels: BE, refactor

#73 #67 - feat: 인증사진 업로드 기능 구현
  client/package-lock.json
  client/src/components/Button.js
  client/src/components/Header.js
  client/src/components/Input.js
  client/src/components/Modal.js
  client/src/index.js
  client/src/pages/Home.js
  client/src/pages/MyChallengeUpload.js
Labels: FE, feat

#74 #44 - feat: 인기챌린지 조회, 무한스크롤 구현
  client/src/components/Loading.js
  client/src/pages/Home.js
Labels: FE, feat

#75 #66 - feat: 마이챌린지 조회, 무한스크롤 구현
  client/src/components/ImageUploader.js
  client/src/components/ProgressBar.js
  client/src/pages/CreateChallenge.js
  client/src/pages/MyChallenge.js
Labels: FE, feat

#76 #65 - feat: 배포환경 구축 - 기존 구현내용 보완
  .github/ISSUE_TEMPLATE/custom-issue-template.md
  .github/pull_request_template.md
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/service/ChallengeService.java
  server/src/main/java/mainproject/domain/challenger/Service/ChallengerService.java
  server/src/main/java/mainproject/domain/image/service/ImageService.java
  server/src/main/java/mainproject/domain/security/config/SecurityConfiguration.java
  server/src/main/java/mainproject/domain/snapshot/Controller/SnapshotController.java
  server/src/main/java/mainproject/domain/snapshot/Service/SnapshotService.java
Labels: BE, feat, refactor

#79 #59 - feat: 카테고리별 챌린지 조회 및 검색 기능 구현
  client/package-lock.json
  client/package.json
  client/src/components/ChallengeItem.js
  client/src/index.css
  client/src/pages/CreateChallenge.js
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/MyChallenge.js
Labels: FE, feat

#80 #42-feat: 로그인 기능 추가 구현
  client/package-lock.json
  client/src/apis/base.js
  client/src/index.css
  client/src/index.js
  client/src/pages/Home.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyPage.js
  client/src/pages/SignIn.js
  client/src/redux/Counter.js
  client/src/redux/store.js
  client/src/redux/userSlice.js
Labels: FE, feat

#85 #65 - feat: 배포환경 구축
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengeDetailResponseDto.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengePostDto.java
  server/src/main/java/mainproject/domain/challenge/entity/Challenge.java
  server/src/main/java/mainproject/domain/challenge/mapper/ChallengeMapper.java
  server/src/main/java/mainproject/domain/challenge/repository/ChallengeRepository.java
  server/src/main/java/mainproject/domain/challenge/service/ChallengeService.java
  server/src/main/java/mainproject/domain/challenger/Dto/ChallengerResponseDto.java
  server/src/main/java/mainproject/domain/challenger/Entity/Challenger.java
  server/src/main/java/mainproject/domain/challenger/Mapper/ChallengerMapper.java
  server/src/main/java/mainproject/domain/challenger/Service/ChallengerService.java
  server/src/main/java/mainproject/domain/snapshot/Controller/SnapshotController.java
  server/src/main/java/mainproject/domain/snapshot/Repository/SnapshotRepository.java
  server/src/main/java/mainproject/domain/snapshot/Service/SnapshotService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/test/java/mainproject/MainProjectApplicationTests.java
Labels: BE, feat, refactor, chore

#86 #81-feat:마이페이지 유저 조회 기능 구현
  client/src/apis/base.js
  client/src/pages/MyPage.js
  client/src/pages/SignIn.js
  client/src/pages/SignUp.js
Labels: FE, feat

#87 #8 - fix: css position 수정
  client/package-lock.json
  client/src/index.css
  client/src/pages/Home.js
  client/src/pages/MyChallenge.js
Labels: FE, fix, design

#88 #81-feat: 마이페이지 프로필 수정 기능
  client/.env
  client/src/apis/base.js
  client/src/components/MypageSetting.js
  client/src/index.css
  client/src/pages/CreateChallenge.js
  client/src/pages/FindPassword.js
  client/src/pages/Home.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyPage.js
  client/src/pages/SignIn.js
  client/src/pages/UserCreateChallenge.js
  client/src/pages/UserPasswordChange.js
  client/src/pages/UserProfileEdit.js
  client/src/redux/userSlice.js
  client/src/router/Router.js
Labels: FE, feat

#93 #60 - fix: 챌린지 관련 에러 수정
  client/package-lock.json
  client/src/App.js
  client/src/components/ChallengeItem.js
  client/src/components/Loading.js
  client/src/components/Logout.js
  client/src/components/NoData.js
  client/src/index.css
  client/src/pages/ChallengeDetail.js
  client/src/pages/CreateChallenge.js
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyChallengeOthers.js
  client/src/router/Router.js
Labels: FE, feat, fix, design

#94 #81-feat: 마이페이지 조회 기능 구현
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/MypageSetting.js
  client/src/pages/MyPage.js
  client/src/pages/SignIn.js
  client/src/pages/SignUp.js
  client/src/pages/UserCompleteChallenge.js
  client/src/pages/UserCreateChallenge.js
  client/src/pages/UserProfileEdit.js
  client/src/redux/userSlice.js
Labels: FE, feat

#91 #70 : 게시판 카테고리별 조회 기능 추가
  server/src/main/java/mainproject/domain/board/controller/BoardController.java
  server/src/main/java/mainproject/domain/board/respository/BoardRepository.java
  server/src/main/java/mainproject/domain/board/service/BoardService.java
  server/src/main/java/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject/domain/comment/repository/CommentRepository.java
  server/src/main/java/mainproject/domain/comment/service/CommentService.java
Labels: BE

#92 #38 Be/Refactor Member 코드 수정 및 SecurtiyConfig 주석 추가
  server/src/main/java/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/mainproject/domain/member/dto/MemberResponseDtoV2.java
  server/src/main/java/mainproject/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject/domain/security/config/SecurityConfiguration.java
Labels: BE, refactor

#96 #92- fix: 게시글 별 댓글 조회 기능 최신순 정렬
  server/src/main/java/mainproject/domain/board/controller/BoardController.java
  server/src/main/java/mainproject/domain/board/respository/BoardRepository.java
  server/src/main/java/mainproject/domain/board/service/BoardService.java
  server/src/main/java/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject/domain/comment/repository/CommentRepository.java
  server/src/main/java/mainproject/domain/comment/service/CommentService.java
Labels: BE

#95 #46-feat: 커뮤니티 댓글 CRUD 구현
  client/.env
  client/src/pages/Community.js
  client/src/pages/CreatePost.js
  client/src/pages/PostDetail.js
Labels: FE, feat, fix

#97 #65 - feat: 기존 구현내용 보완 - 인증사진 등록시 챌린지 빈도수 초과여부 검증 구현
  server/build.gradle
  server/src/main/java/mainproject/domain/image/controller/ImageController.java
  server/src/main/java/mainproject/domain/image/dto/ImageResponseDto.java
  server/src/main/java/mainproject/domain/snapshot/Service/SnapshotService.java
  server/src/main/java/mainproject/global/exception/ExceptionCode.java
  server/src/main/resources/application-local.yml
Labels: BE, feat

#99 #38 refactor: 엑세스 토큰 만료시간 수정
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
Labels: BE, refactor

#98 #66 - fix: 챌린지 관련 에러 수정
  client/.env
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/pages/ChallengeDetail.js
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/MyChallengeOthers.js
Labels: FE, feat, fix

#102 #65 - feat: 배포환경 구축
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengePostDto.java
  server/src/main/java/mainproject/domain/image/controller/ImageController.java
  server/src/main/java/mainproject/domain/image/dto/ImageResponseDto.java
  server/src/main/java/mainproject/domain/image/entity/Image.java
  server/src/main/java/mainproject/domain/image/service/ImageService.java
  server/src/main/resources/application-server.yml
Labels: BE, feat, refactor

#105 #21- fix: category 생활 -> 생활습관 수정
  server/src/main/java/mainproject/domain/board/controller/BoardController.java
  server/src/main/java/mainproject/global/category/Category.java
Labels: BE

#104 #66 - fix: 토큰 관련 에러 수정
  client/.gitignore
  client/src/pages/ChallengeDetail.js
  client/src/pages/Home.js
  client/src/pages/MyChallenge.js
Labels: FE, feat, fix

#108 #81-feat:마이페이지 기능구현
  client/package.json
  client/src/components/Challenge.js
  client/src/pages/MyPage.js
  client/src/pages/UserCompleteChallenge.js
  client/src/pages/UserCreateChallenge.js
  client/src/pages/UserProfileEdit.js
Labels: FE, feat

#110 #68 - feat: 랜덤 이미지 적용
  client/cors.json
  client/src/components/Category.js
  client/src/components/ChallengeItem.js
  client/src/images/random.js
  client/src/pages/ChallengeDetail.js
  client/src/pages/CreateChallenge.js
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyChallengeOthers.js
  client/src/pages/MyChallengeUpload.js
Labels: FE, feat, fix

#111 #81-feat:생성/완료 챌린지 랜덤 이미지 적용
  client/.env
  client/package-lock.json
  client/package.json
  client/public/images/profileImg0.png
  client/public/images/profileImg1.png
  client/public/images/profileImg2.png
  client/public/images/profileImg3.png
  client/src/apis/base.js
  client/src/components/Challenge.js
  client/src/pages/MyPage.js
  client/src/pages/SignIn.js
  client/src/pages/UserCompleteChallenge.js
  client/src/pages/UserCreateChallenge.js
Labels: FE, feat

#113 #45-fix: 커뮤니티 글 CRUD 서버 통신 관련 수정
  client/.env
Labels: FE, feat, fix

#114 #60 - feat: 서버 통신 수정
  client/src/pages/CreateChallenge.js
Labels: FE, feat, fix

#120 #59 - feat: 무한스크롤 수정
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
Labels: FE, fix

#117 docs: README.md 기술스택, Swagger Info 수정
  README.md
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/repository/ChallengeRepository.java
  server/src/main/java/mainproject/domain/challenge/service/ChallengeService.java
  server/src/main/java/mainproject/global/config/SwaggerConfiguration.java
Labels: BE, docs, refactor

#122 refactor: 챌린지 전체 조회 메서드에서 무한스크롤 미적용
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/repository/ChallengeRepository.java
  server/src/main/java/mainproject/domain/challenge/service/ChallengeService.java
Labels: BE, refactor

#125 #45 - fix : 페이지 이동 관련 오류 수정
  client/src/pages/Community.js
  client/src/pages/CommunityCategoryBoard.js
  client/src/pages/CreatePost.js
  client/src/pages/PostDetail.js
Labels: FE, fix

#126 #59 - feat: 무한스크롤 및 통신 수정
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
Labels: FE, fix
