Repository codestates-seb/seb41_main_013, pull requests merged in 2023-02, with the labels that each got.

#128 #45&46&47 - feat&fix : 글/댓글 CRUD 구현, 글 검색 기능 추가
  client/package-lock.json
  client/src/components/Avatar.js
  client/src/components/Category.js
  client/src/components/Comment.js
  client/src/components/SearchInput.js
  client/src/components/WriteComment.js
  client/src/pages/Community.js
  client/src/pages/CommunityCategoryBoard.js
  client/src/pages/PostDetail.js
  client/src/pages/UpdatePost.js
Labels: FE, feat, fix, refactor

#132 #60 - style: 콘솔로그 제거
  client/src/images/running.JPG
  client/src/pages/ChallengeDetail.js
  client/src/pages/CreateChallenge.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyChallengeUpload.js
Labels: FE, style

#129 #65 - feat: 기존 구현내용 보완
  server/src/main/java/mainproject/domain/board/controller/BoardController.java
  server/src/main/java/mainproject/domain/board/dto/BoardResponseDto.java
  server/src/main/java/mainproject/domain/board/entity/Board.java
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengeDetailResponseDto.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengeResponseDto.java
  server/src/main/java/mainproject/domain/challenger/Controller/ChallengerController.java
  server/src/main/java/mainproject/domain/challenger/Dto/ChallengerDetailResponseDto.java
  server/src/main/java/mainproject/domain/challenger/Dto/ChallengerResponseDto.java
  server/src/main/java/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject/domain/comment/dto/CommentResponseDto.java
  server/src/main/java/mainproject/domain/image/controller/ImageController.java
  server/src/main/java/mainproject/domain/image/dto/ImageResponseDto.java
  server/src/main/java/mainproject/domain/image/entity/Image.java
  server/src/main/java/mainproject/domain/image/service/ImageService.java
  server/src/main/java/mainproject/domain/member/controller/MemberController.java
  server/src/main/java/mainproject/domain/member/dto/MemberResponseDto.java
  server/src/main/java/mainproject/domain/snapshot/Controller/SnapshotController.java
  server/src/main/java/mainproject/domain/snapshot/Dto/SnapshotResponseDto.java
  server/src/main/java/mainproject/global/exception/ExceptionCode.java
Labels: BE, feat

#133 #65 - feat: 기존 구현내용 보완
  server/src/main/java/mainproject/domain/image/service/ImageService.java
Labels: BE, feat

#136 #65 - feat: 기존 구현내용 보완
  server/src/main/java/mainproject/domain/board/controller/BoardController.java
  server/src/main/java/mainproject/domain/challenge/controller/ChallengeController.java
  server/src/main/java/mainproject/domain/challenger/Controller/ChallengerController.java
  server/src/main/java/mainproject/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject/domain/image/service/ImageService.java
  server/src/main/java/mainproject/domain/snapshot/Controller/SnapshotController.java
Labels: BE, feat

#137 #65 - feat: 배포환경 구축
  server/appspec.yml
  server/scripts/deploy.sh
  server/src/main/java/mainproject/domain/board/dto/BoardPostDto.java
  server/src/main/java/mainproject/domain/challenge/dto/ChallengePostDto.java
  server/src/main/java/mainproject/domain/challenger/Mapper/ChallengerMapper.java
  server/src/main/java/mainproject/domain/image/service/ImageService.java
  server/src/main/java/mainproject/domain/member/dto/MemberPostDto.java
Labels: BE, feat, refactor

#135 #10 - fix : 유저 이미지 관련 파일 추가 및 수정
  client/src/components/Avatar.js
  client/src/components/Comment.js
  client/src/components/PostSummary.js
  client/src/components/WriterInfo.js
  client/src/images/profileImg10.png
  client/src/images/profileImg11.png
  client/src/images/profileImg12.png
  client/src/images/profileImg13.png
  client/src/images/profileImg14.png
  client/src/images/profileImg15.png
  client/src/images/profileImg4.png
  client/src/images/profileImg5.png
  client/src/images/profileImg6.png
  client/src/images/profileImg7.png
  client/src/images/profileImg8.png
  client/src/images/profileImg9.png
  client/src/pages/Community.js
  client/src/pages/CommunityCategoryBoard.js
  client/src/pages/CreatePost.js
  client/src/pages/MyPage.js
  client/src/pages/PostDetail.js
  client/src/pages/UpdatePost.js
Labels: FE, feat, style

#139 #127-repactor: 마이페이지 프로필 사진 변경
  client/.env
  client/src/pages/MyPage.js
  client/src/pages/SignUp.js
  client/src/pages/UserCompleteChallenge.js
  client/src/pages/UserCreateChallenge.js
  client/src/pages/UserProfileEdit.js
  client/src/redux/userSlice.js
Labels: FE, feat, refactor

#141 #67 - fix: 이미지 업로드 기능 수정
  client/src/pages/ChallengeDetail.js
  client/src/pages/CreateChallenge.js
  client/src/pages/Home.js
  client/src/pages/HomeCategoryBoard.js
  client/src/pages/MyChallenge.js
  client/src/pages/MyChallengeOthers.js
  client/src/pages/MyChallengeUpload.js
Labels: FE, fix
